export const citiesData = [
  "Ahmedabad",
  "GIFT City",
  "Dholera",
  "Mumbai",
  // "Port Blair",
  // "Visakhapatnam",
  // "Vijayawada",
  // "Guntur",
  // "Tirupati",
  // "Nellore",
  // "Itanagar",
  // "Naharlagun",
  // "Guwahati",
  // "Silchar",
  // "Dibrugarh",
  // "Patna",
  // "Gaya",
  // "Bhagalpur",
  // "Chandigarh",
  // "Raipur",
  // "Bilaspur",
  // "Durg",
  // "New Delhi",
  // "Delhi",
  // "Panaji",
  // "Margao",
  // "Surat",
  // "Vadodara",
  // "Gurgaon",
  // "Faridabad",
  // "Shimla",
  // "Dharamshala",
  // "Srinagar",
  // "Jammu",
  // "Ranchi",
  // "Jamshedpur",
  // "Bangalore",
  // "Mysore",
  // "Mangalore",
  // "Thiruvananthapuram",
  // "Kochi",
  // "Kozhikode",
  // "Leh",
  // "Bhopal",
  // "Indore",
  // "Gwalior",
  // "Pune",
  // "Nagpur",
  // "Imphal",
  // "Shillong",
  // "Aizawl",
  // "Kohima",
  // "Bhubaneswar",
  // "Puducherry",
  // "Amritsar",
  // "Ludhiana",
  // "Jaipur",
  // "Jodhpur",
  // "Udaipur",
  // "Gangtok",
  // "Chennai",
  // "Coimbatore",
  // "Madurai",
  // "Hyderabad",
  // "Warangal",
  // "Agartala",
  // "Lucknow",
  // "Kanpur",
  // "Varanasi",
  // "Dehradun",
  // "Haridwar",
  // "Kolkata",
  // "Howrah",
];
