import developerInnerImg from "../assets/developers/developerInner.jpg";
import developer1 from "../assets/developers/developer1.jpg";
import developer2 from "../assets/developers/developer2.jpg";
import developer3 from "../assets/developers/developer3.jpg";
import developer4 from "../assets/developers/developer4.jpg";
// projects
import commercialImg1 from "../assets/home/commercial1.jpg";
import commercialImg2 from "../assets/home/commercial2.jpg";
import commercialImg3 from "../assets/home/commercial3.jpg";
import commercialImg4 from "../assets/home/commercial4.jpg";

export const developersData = [
  {
    id: 1,
    title: "Gupta Properties Group",
    route: "gupta-properties-group",
    location: "Corp Build Mani",
    experience: "7 Years Experience",
    description: `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie, dictum est a, mattis tellus. Sed dignissim, metus nec fringilla accumsan, risus sem sollicitudin lacus, ut interdum tellus elit sed risus. Maecenas eget condimentum velit, sit amet feugiat lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent auctor purus luctus enim egestas, ac scelerisque ante pulvinar. Donec ut rhoncus ex. Suspendisse ac rhoncus nisl, eu tempor urna. Curabitur vel bibendum lorem. Morbi convallis convallis diam sit amet lacinia. Aliquam in elementum tellus.</p>`,
    featured_img: developer1,
    inner_page_image: developerInnerImg,
    project_id: "",
    related_projects: [
      {
        id: 1,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 2,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 3,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 4,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 5,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 6,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 7,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 8,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 9,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 10,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg4,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 11,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg2,
        price: "1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 12,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
    ],
    seo: {
      meta_title: "Gupta Properties Group",
      meta_description: "Gupta Properties Group",
      schema_markup: "",
    },
  },
  {
    id: 2,
    title: "Multiplex Developer",
    route: "multiplex-developer",
    location: "Apex Corp Zone 1",
    experience: "6 Years Experience",
    description: `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie, dictum est a, mattis tellus. Sed dignissim, metus nec fringilla accumsan, risus sem sollicitudin lacus, ut interdum tellus elit sed risus. Maecenas eget condimentum velit, sit amet feugiat lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent auctor purus luctus enim egestas, ac scelerisque ante pulvinar. Donec ut rhoncus ex. Suspendisse ac rhoncus nisl, eu tempor urna. Curabitur vel bibendum lorem. Morbi convallis convallis diam sit amet lacinia. Aliquam in elementum tellus.</p>`,
    featured_img: developer2,
    inner_page_image: developerInnerImg,
    project_id: "",
    related_projects: [
      {
        id: 1,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 2,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 3,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 4,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 5,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 6,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 7,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 8,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 9,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 10,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg4,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 11,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg2,
        price: "1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 12,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
    ],
    seo: {
      meta_title: "Multiplex Developer",
      meta_description: "Multiplex Developer",
      schema_markup: "",
    },
  },
  {
    id: 3,
    title: "Makrana Properties Group",
    route: "makrana-properties-group",
    location: "Multiplex Zone 2",
    experience: "4 Years Experience",
    description: `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie, dictum est a, mattis tellus. Sed dignissim, metus nec fringilla accumsan, risus sem sollicitudin lacus, ut interdum tellus elit sed risus. Maecenas eget condimentum velit, sit amet feugiat lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent auctor purus luctus enim egestas, ac scelerisque ante pulvinar. Donec ut rhoncus ex. Suspendisse ac rhoncus nisl, eu tempor urna. Curabitur vel bibendum lorem. Morbi convallis convallis diam sit amet lacinia. Aliquam in elementum tellus.</p>`,
    featured_img: developer3,
    inner_page_image: developerInnerImg,
    project_id: "",
    related_projects: [
      {
        id: 1,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 2,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 3,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 4,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 5,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 6,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 7,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 8,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 9,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 10,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg4,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 11,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg2,
        price: "1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 12,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
    ],
    seo: {
      meta_title: "Makrana Properties Group",
      meta_description: "Makrana Properties Group",
      schema_markup: "",
    },
  },
  {
    id: 4,
    title: "Mania Group",
    route: "mania-group",
    location: "Headquarter Mania",
    experience: "5 Years Experience",
    description: `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie, dictum est a, mattis tellus. Sed dignissim, metus nec fringilla accumsan, risus sem sollicitudin lacus, ut interdum tellus elit sed risus. Maecenas eget condimentum velit, sit amet feugiat lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent auctor purus luctus enim egestas, ac scelerisque ante pulvinar. Donec ut rhoncus ex. Suspendisse ac rhoncus nisl, eu tempor urna. Curabitur vel bibendum lorem. Morbi convallis convallis diam sit amet lacinia. Aliquam in elementum tellus.</p>`,
    featured_img: developer4,
    inner_page_image: developerInnerImg,
    project_id: "",
    related_projects: [
      {
        id: 1,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 2,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 3,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 4,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 5,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 6,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 7,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 8,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 9,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 10,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg4,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 11,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg2,
        price: "1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 12,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
    ],
    seo: {
      meta_title: "Gupta Properties Group",
      meta_description: "Gupta Properties Group",
      schema_markup: "",
    },
  },
  {
    id: 5,
    title: "Multiplex Developer",
    route: "multiplex-developer",
    location: "Apex Corp Zone 1",
    experience: "6 Years Experience",
    description: `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie, dictum est a, mattis tellus. Sed dignissim, metus nec fringilla accumsan, risus sem sollicitudin lacus, ut interdum tellus elit sed risus. Maecenas eget condimentum velit, sit amet feugiat lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent auctor purus luctus enim egestas, ac scelerisque ante pulvinar. Donec ut rhoncus ex. Suspendisse ac rhoncus nisl, eu tempor urna. Curabitur vel bibendum lorem. Morbi convallis convallis diam sit amet lacinia. Aliquam in elementum tellus.</p>`,
    featured_img: developer2,
    inner_page_image: developerInnerImg,
    project_id: "",
    related_projects: [
      {
        id: 1,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 2,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 3,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 4,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 5,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 6,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 7,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 8,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 9,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 10,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg4,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 11,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg2,
        price: "1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 12,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
    ],
    seo: {
      meta_title: "Multiplex Developer",
      meta_description: "Multiplex Developer",
      schema_markup: "",
    },
  },
  {
    id: 6,
    title: "Mania Group",
    route: "mania-group",
    location: "Headquarter Mania",
    experience: "5 Years Experience",
    description: `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie, dictum est a, mattis tellus. Sed dignissim, metus nec fringilla accumsan, risus sem sollicitudin lacus, ut interdum tellus elit sed risus. Maecenas eget condimentum velit, sit amet feugiat lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent auctor purus luctus enim egestas, ac scelerisque ante pulvinar. Donec ut rhoncus ex. Suspendisse ac rhoncus nisl, eu tempor urna. Curabitur vel bibendum lorem. Morbi convallis convallis diam sit amet lacinia. Aliquam in elementum tellus.</p>`,
    featured_img: developer4,
    inner_page_image: developerInnerImg,
    project_id: "",
    related_projects: [
      {
        id: 1,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 2,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 3,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 4,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 5,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 6,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 7,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 8,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 9,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 10,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg4,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 11,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg2,
        price: "1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 12,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
    ],
    seo: {
      meta_title: "Gupta Properties Group",
      meta_description: "Gupta Properties Group",
      schema_markup: "",
    },
  },
  {
    id: 7,
    title: "Gupta Properties Group",
    route: "gupta-properties-group",
    location: "Corp Build Mani",
    experience: "7 Years Experience",
    description: `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie, dictum est a, mattis tellus. Sed dignissim, metus nec fringilla accumsan, risus sem sollicitudin lacus, ut interdum tellus elit sed risus. Maecenas eget condimentum velit, sit amet feugiat lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent auctor purus luctus enim egestas, ac scelerisque ante pulvinar. Donec ut rhoncus ex. Suspendisse ac rhoncus nisl, eu tempor urna. Curabitur vel bibendum lorem. Morbi convallis convallis diam sit amet lacinia. Aliquam in elementum tellus.</p>`,
    featured_img: developer1,
    inner_page_image: developerInnerImg,
    project_id: "",
    related_projects: [
      {
        id: 1,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 2,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 3,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 4,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 5,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 6,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 7,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 8,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 9,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 10,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg4,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 11,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg2,
        price: "1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 12,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
    ],
    seo: {
      meta_title: "Gupta Properties Group",
      meta_description: "Gupta Properties Group",
      schema_markup: "",
    },
  },
  {
    id: 8,
    title: "Makrana Properties Group",
    route: "makrana-properties-group",
    location: "Multiplex Zone 2",
    experience: "4 Years Experience",
    description: `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie, dictum est a, mattis tellus. Sed dignissim, metus nec fringilla accumsan, risus sem sollicitudin lacus, ut interdum tellus elit sed risus. Maecenas eget condimentum velit, sit amet feugiat lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent auctor purus luctus enim egestas, ac scelerisque ante pulvinar. Donec ut rhoncus ex. Suspendisse ac rhoncus nisl, eu tempor urna. Curabitur vel bibendum lorem. Morbi convallis convallis diam sit amet lacinia. Aliquam in elementum tellus.</p>`,
    featured_img: developer3,
    inner_page_image: developerInnerImg,
    project_id: "",
    related_projects: [
      {
        id: 1,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 2,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 3,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 4,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 5,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 6,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 7,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 8,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 9,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 10,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg4,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 11,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg2,
        price: "1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 12,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
    ],
    seo: {
      meta_title: "Makrana Properties Group",
      meta_description: "Makrana Properties Group",
      schema_markup: "",
    },
  },
  {
    id: 9,
    title: "Makrana Properties Group",
    route: "makrana-properties-group",
    location: "Multiplex Zone 2",
    experience: "4 Years Experience",
    description: `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie, dictum est a, mattis tellus. Sed dignissim, metus nec fringilla accumsan, risus sem sollicitudin lacus, ut interdum tellus elit sed risus. Maecenas eget condimentum velit, sit amet feugiat lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent auctor purus luctus enim egestas, ac scelerisque ante pulvinar. Donec ut rhoncus ex. Suspendisse ac rhoncus nisl, eu tempor urna. Curabitur vel bibendum lorem. Morbi convallis convallis diam sit amet lacinia. Aliquam in elementum tellus.</p>`,
    featured_img: developer3,
    inner_page_image: developerInnerImg,
    project_id: "",
    related_projects: [
      {
        id: 1,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 2,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 3,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 4,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 5,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 6,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 7,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 8,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 9,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 10,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg4,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 11,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg2,
        price: "1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 12,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
    ],
    seo: {
      meta_title: "Makrana Properties Group",
      meta_description: "Makrana Properties Group",
      schema_markup: "",
    },
  },
  {
    id: 10,
    title: "Multiplex Developer",
    route: "multiplex-developer",
    location: "Apex Corp Zone 1",
    experience: "6 Years Experience",
    description: `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie, dictum est a, mattis tellus. Sed dignissim, metus nec fringilla accumsan, risus sem sollicitudin lacus, ut interdum tellus elit sed risus. Maecenas eget condimentum velit, sit amet feugiat lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent auctor purus luctus enim egestas, ac scelerisque ante pulvinar. Donec ut rhoncus ex. Suspendisse ac rhoncus nisl, eu tempor urna. Curabitur vel bibendum lorem. Morbi convallis convallis diam sit amet lacinia. Aliquam in elementum tellus.</p>`,
    featured_img: developer2,
    inner_page_image: developerInnerImg,
    project_id: "",
    related_projects: [
      {
        id: 1,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 2,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 3,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 4,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 5,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 6,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 7,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 8,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 9,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 10,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg4,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 11,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg2,
        price: "1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 12,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
    ],
    seo: {
      meta_title: "Multiplex Developer",
      meta_description: "Multiplex Developer",
      schema_markup: "",
    },
  },
  {
    id: 11,
    title: "Gupta Properties Group",
    route: "gupta-properties-group",
    location: "Corp Build Mani",
    experience: "7 Years Experience",
    description: `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie, dictum est a, mattis tellus. Sed dignissim, metus nec fringilla accumsan, risus sem sollicitudin lacus, ut interdum tellus elit sed risus. Maecenas eget condimentum velit, sit amet feugiat lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent auctor purus luctus enim egestas, ac scelerisque ante pulvinar. Donec ut rhoncus ex. Suspendisse ac rhoncus nisl, eu tempor urna. Curabitur vel bibendum lorem. Morbi convallis convallis diam sit amet lacinia. Aliquam in elementum tellus.</p>`,
    featured_img: developer1,
    inner_page_image: developerInnerImg,
    project_id: "",
    related_projects: [
      {
        id: 1,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 2,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 3,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 4,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 5,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 6,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 7,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 8,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 9,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 10,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg4,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 11,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg2,
        price: "1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 12,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
    ],
    seo: {
      meta_title: "Gupta Properties Group",
      meta_description: "Gupta Properties Group",
      schema_markup: "",
    },
  },
  {
    id: 12,
    title: "Mania Group",
    route: "mania-group",
    location: "Headquarter Mania",
    experience: "5 Years Experience",
    description: `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie, dictum est a, mattis tellus. Sed dignissim, metus nec fringilla accumsan, risus sem sollicitudin lacus, ut interdum tellus elit sed risus. Maecenas eget condimentum velit, sit amet feugiat lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent auctor purus luctus enim egestas, ac scelerisque ante pulvinar. Donec ut rhoncus ex. Suspendisse ac rhoncus nisl, eu tempor urna. Curabitur vel bibendum lorem. Morbi convallis convallis diam sit amet lacinia. Aliquam in elementum tellus.</p>`,
    featured_img: developer4,
    inner_page_image: developerInnerImg,
    project_id: "",
    related_projects: [
      {
        id: 1,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 2,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 3,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 4,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 5,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 6,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 7,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 8,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 9,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
      {
        id: 10,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg4,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 11,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg2,
        price: "1Cr",
        location: "Ahmedabad, Zone 1",
      },
      {
        id: 12,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
      },
    ],
    seo: {
      meta_title: "Gupta Properties Group",
      meta_description: "Gupta Properties Group",
      schema_markup: "",
    },
  },
];

export default developersData;
