// residential
import residentialImg1 from "../assets/home/residential1.jpg";
import residentialImg2 from "../assets/home/residential2.jpg";
import residentialImg3 from "../assets/home/residential3.jpg";
import residentialImg4 from "../assets/home/residential4.jpg";
// commercial
import commercialImg1 from "../assets/home/commercial1.jpg";
import commercialImg2 from "../assets/home/commercial2.jpg";
import commercialImg3 from "../assets/home/commercial3.jpg";
import commercialImg4 from "../assets/home/commercial4.jpg";

export const locationsData = [
  {
    id: 1,
    title: "Zone 1",
    route: "zone-1",
    banner_image: "",
    projects_list: [
      {
        id: 1,
        title: "Equestrian Family Home",
        route: "equestrian-family-home",
        featured_img: residentialImg1,
        price: "₹ 95L - 1Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Residential",
          route: "residential",
        },
      },
      {
        id: 2,
        title: "Luxury Villa",
        route: "luxury-villa",
        featured_img: residentialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
        category: {
          title: "Residential",
          route: "residential",
        },
      },
      {
        id: 3,
        title: "Luxury Flat",
        route: "luxury-flat",
        featured_img: residentialImg3,
        price: "₹ 95L - 1Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Residential",
          route: "residential",
        },
      },
      {
        id: 4,
        title: "Rocksolid Family Home",
        route: "rocksolid-family-home",
        featured_img: residentialImg4,
        price: "₹ 2Cr",
        location: "Ahmedabad, Zone 1",
        category: {
          title: "Residential",
          route: "residential",
        },
      },
      {
        id: 5,
        title: "Luxury Villa",
        route: "luxury-villa",
        featured_img: residentialImg2,
        price: "₹ 95L - 1Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Residential",
          route: "residential",
        },
      },
      {
        id: 6,
        title: "Rocksolid Family Home",
        route: "rocksolid-family-home",
        featured_img: residentialImg4,
        price: "₹ 2Cr",
        location: "Ahmedabad, Zone 1",
        category: {
          title: "Residential",
          route: "residential",
        },
      },
      {
        id: 7,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Commercial",
          route: "commercial",
        },
      },
      {
        id: 8,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Commercial",
          route: "commercial",
        },
      },
      {
        id: 9,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Commercial",
          route: "commercial",
        },
      },
      {
        id: 10,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg4,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
        category: {
          title: "Commercial",
          route: "commercial",
        },
      },
      {
        id: 11,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg2,
        price: "1Cr",
        location: "Ahmedabad, Zone 1",
        category: {
          title: "Commercial",
          route: "commercial",
        },
      },
      {
        id: 12,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Commercial",
          route: "commercial",
        },
      },
    ],
    seo: {
      meta_title: "Zone 1 | NewEdge Realty",
      meta_description: "Zone 1 | NewEdge Realty",
      schema_markup: "",
    },
  },
  {
    id: 2,
    title: "Zone 2",
    route: "zone-2",
    banner_image: "",
    projects_list: [
      {
        id: 1,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Commercial",
          route: "commercial",
        },
      },
      {
        id: 2,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
        category: {
          title: "Commercial",
          route: "commercial",
        },
      },
      {
        id: 3,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Commercial",
          route: "commercial",
        },
      },
      {
        id: 4,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
        category: {
          title: "Commercial",
          route: "commercial",
        },
      },
      {
        id: 5,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
        category: {
          title: "Commercial",
          route: "commercial",
        },
      },
      {
        id: 6,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
        category: {
          title: "Commercial",
          route: "commercial",
        },
      },
      {
        id: 7,
        title: "Equestrian Family Home",
        route: "equestrian-family-home",
        featured_img: residentialImg1,
        price: "₹ 95L - 1Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Residential",
          route: "residential",
        },
      },
      {
        id: 8,
        title: "Luxury Flat",
        route: "luxury-flat",
        featured_img: residentialImg3,
        price: "₹ 95L - 1Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Residential",
          route: "residential",
        },
      },
      {
        id: 9,
        title: "Equestrian Family Home",
        route: "equestrian-family-home",
        featured_img: residentialImg1,
        price: "₹ 95L - 1Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Residential",
          route: "residential",
        },
      },
      {
        id: 10,
        title: "Luxury Flat",
        route: "luxury-flat",
        featured_img: residentialImg3,
        price: "₹ 95L - 1Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Residential",
          route: "residential",
        },
      },
      {
        id: 11,
        title: "Rocksolid Family Home",
        route: "rocksolid-family-home",
        featured_img: residentialImg4,
        price: "₹ 2Cr",
        location: "Ahmedabad, Zone 1",
        category: {
          title: "Residential",
          route: "residential",
        },
      },
      {
        id: 12,
        title: "Luxury Villa",
        route: "luxury-villa",
        featured_img: residentialImg4,
        price: "₹ 95L - 1Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Residential",
          route: "residential",
        },
      },
    ],
    seo: {
      meta_title: "Zone 2 | NewEdge Realty",
      meta_description: "Zone 2 | NewEdge Realty",
      schema_markup: "",
    },
  },
  {
    id: 3,
    title: "Zone 3",
    route: "zone-3",
    banner_image: "",
    projects_list: [
      {
        id: 1,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Pre-Leased",
          route: "pre-leased",
        },
      },
      {
        id: 2,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
        category: {
          title: "Pre-Leased",
          route: "pre-leased",
        },
      },
      {
        id: 3,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Pre-Leased",
          route: "pre-leased",
        },
      },
      {
        id: 4,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
        category: {
          title: "Pre-Leased",
          route: "pre-leased",
        },
      },
      {
        id: 5,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
        category: {
          title: "Pre-Leased",
          route: "pre-leased",
        },
      },
      {
        id: 6,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
        category: {
          title: "Pre-Leased",
          route: "pre-leased",
        },
      },
      {
        id: 7,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Farmhouse",
          route: "farmhouse",
        },
      },
      {
        id: 8,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Farmhouse",
          route: "farmhouse",
        },
      },
      {
        id: 9,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Farmhouse",
          route: "farmhouse",
        },
      },
      {
        id: 10,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg4,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
        category: {
          title: "Farmhouse",
          route: "farmhouse",
        },
      },
      {
        id: 11,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg2,
        price: "1Cr",
        location: "Ahmedabad, Zone 1",
        category: {
          title: "Farmhouse",
          route: "farmhouse",
        },
      },
      {
        id: 12,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Farmhouse",
          route: "farmhouse",
        },
      },
    ],
    seo: {
      meta_title: "Zone 3 | NewEdge Realty",
      meta_description: "Zone 3 | NewEdge Realty",
      schema_markup: "",
    },
  },
  {
    id: 4,
    title: "Zone 4",
    route: "zone-4",
    banner_image: "",
    projects_list: [
      {
        id: 1,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Farmhouse",
          route: "farmhouse",
        },
      },
      {
        id: 2,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
        category: {
          title: "Farmhouse",
          route: "farmhouse",
        },
      },
      {
        id: 3,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Farmhouse",
          route: "farmhouse",
        },
      },
      {
        id: 4,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
        category: {
          title: "Farmhouse",
          route: "farmhouse",
        },
      },
      {
        id: 5,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg2,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
        category: {
          title: "Farmhouse",
          route: "farmhouse",
        },
      },
      {
        id: 6,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg4,
        price: "₹ 1Cr - 2Cr",
        location: "Ahmedabad, Zone 1",
        category: {
          title: "Farmhouse",
          route: "farmhouse",
        },
      },
      {
        id: 7,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Pre-Leased",
          route: "pre-leased",
        },
      },
      {
        id: 8,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Pre-Leased",
          route: "pre-leased",
        },
      },
      {
        id: 9,
        title: "Corp Build Mani",
        route: "corp-build-mani",
        featured_img: commercialImg1,
        price: "₹ 95L",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Pre-Leased",
          route: "pre-leased",
        },
      },
      {
        id: 10,
        title: "Apex Corp Zone 1",
        route: "apex-corp-zone-1",
        featured_img: commercialImg4,
        price: "₹ 1Cr",
        location: "Ahmedabad, Zone 1",
        category: {
          title: "Pre-Leased",
          route: "pre-leased",
        },
      },
      {
        id: 11,
        title: "Headquarter Mania",
        route: "headquarter-mania",
        featured_img: commercialImg2,
        price: "1Cr",
        location: "Ahmedabad, Zone 1",
        category: {
          title: "Pre-Leased",
          route: "pre-leased",
        },
      },
      {
        id: 12,
        title: "Multiplex Zone 2",
        route: "multiplex-zone-2",
        featured_img: commercialImg3,
        price: "₹ 2Cr",
        location: "Maninagar, Zone 1, Ahmedabad",
        category: {
          title: "Pre-Leased",
          route: "pre-leased",
        },
      },
    ],
    seo: {
      meta_title: "Zone 4 | NewEdge Realty",
      meta_description: "Zone 4 | NewEdge Realty",
      schema_markup: "",
    },
  },
];

export default locationsData;
